[Feature ] Formfillperson
i4BSolutions/hope-fuel pull request #70
Opened 2024-12-17 08:20 UTC by aye-nyeinSan

This PR has problem using the env file for AWS credentials key necessary for the AWS Cognito service. 
it is resolved if env variables are not used and implement directly in the component.

2025-01-31 16:59 UTC, kaungphyowai commented
@aye-nyeinSan This has a lot of files to review.

If you can reduce the file for the PR to review, that would be great.

Also there is a conflict. Can you resolve it for me?

2025-01-31 17:01 UTC, kaungphyowai requested changes
Please Change the amount of file number needed to be reivew.

Also make sure that All of the branches are in sync with github and local git repo.

If it helps, pull another request.

2025-01-31 17:30 UTC, kaungphyowai commented
PLEASE ALSO MENTION THE ISSUE NO.

2025-02-01 05:14 UTC, aye-nyeinSan commented
@kaungphyowai 
"I propose that this pull request should be closed with a comment, as this requirement was requested in a previous sprint long ago."

2025-02-01 05:14 UTC, closed without merging